version: 2
jobs:
  build:
    machine: true    

    working_directory: ~/repo

    steps:
      - checkout
      
      - run: 
          name: Install flathub SDK
          command: |
              docker run --privileged --volume "${PWD}":/tmp/sdk/ --name fb -it -d flatpak/flatpak-builder:base /bin/bash
              docker exec -it fb bash -c 'flatpak install flathub org.freedesktop.Sdk/i386/1.6 &&
              flatpak install flathub org.freedesktop.Sdk/x86_64/1.6 &&
              flatpak install flathub org.freedesktop.Platform/i386/1.6 &&
              flatpak install flathub org.freedesktop.Platform/x86_64/1.6'            

      - run: 
          name: Setup winepak repo
          command: |              
              docker exec -it fb bash -c 'cd /tmp/sdk/ && flatpak remote-add --no-gpg-verify winepak winepak-repo'
                   
      - run: 
          name: Build org.winepak.Sdk/i386/3.0
          command: |
              docker exec -it fb bash -c 'cd /tmp/sdk && flatpak-builder \
                  --arch=i386                                            \
                  --ccache                                               \
                  --force-clean                                          \
                  --repo=winepak-repo                                    \
                  winepak-build                                          \
                  org.winepak.Sdk.yml'
      - run:
          name: Build org.winepak.Sdk/x86_64/3.0
          command: |
             docker exec -it fb bash -c 'cd /tmp/sdk && flatpak-builder \
                  --arch=x86_64                                         \
                  --ccache                                              \
                  --force-clean                                         \
                  --repo=winepak-repo                                   \
                  winepak-build                                         \
                  org.winepak.Sdk.yml'
      - run:
          name: Build org.winepak.Platform.Compat32/x86_64/3.0
          command: |
             docker exec -it fb bash -c 'cd /tmp/sdk && flatpak build-commit-from \
                  --src-ref=runtime/org.winepak.Platform/i386/3.0                 \
                  winepak-repo                                                    \
                  runtime/org.winepak.Platform.Compat32/x86_64/3.0'
      - run:
          name: Build org.winepak.Platform.Wine/i386/3.8-staging
          command: |
             docker exec -it fb bash -c 'cd /tmp/sdk && flatpak-builder \
                  --arch=i386                                           \
                  --ccache                                              \
                  --force-clean                                         \
                  --repo=winepak-repo                                   \
                  winepak-build                                         \
                  wine/3.8-staging/org.winepak.Platform.Wine.yml'
      - run:
          name: Build org.winepak.Platform.Wine/x86_64/3.8-staging
          command: |
             docker exec -it fb bash -c 'cd /tmp/sdk && flatpak-builder \
                  --arch=x86_64                                         \
                  --ccache                                              \
                  --force-clean                                         \
                  --repo=winepak-repo                                   \
                  winepak-build                                         \
                  wine/3.8-staging/org.winepak.Platform.Wine.yml'
      - run:
          name: Build org.winepak.Platform.Wine.Compat32/x86_64/3.8-staging
          command: |
             docker exec -it fb bash -c 'cd /tmp/sdk && flatpak build-commit-from \
                  --src-ref=runtime/org.winepak.Platform.Wine/i386/3.8-staging    \
                  winepak-repo                                                    \
                  runtime/org.winepak.Platform.Wine.Compat32/x86_64/3.8-staging'

